---
title: "Week 10"
subtitle: "Text as Data I: Description and Topics"
description: ""
author: "Tiago Ventura"
date: "11/07/2023"
#listing:
  # - id: slides
  #   contents:
  #     - ../slides/week-01/*.qmd
  #   type: table
  #   fields: [title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     title: "Topic"
  #     date: "Date"
  #   sort: [filename]
  #   sort-ui: false
  #   filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

-   Text analysis I: Counting, Describing and Fiting Topics [html](/lecture_notes/week-11/_week-11_text.html) -- <a href="/lecture_notes/week-11/_week-11_text.ipynb" download> Jupyter Notebook </a>

# Slides

-   [Text analysis I](/slides/week-11.html)

# Readings

**Required Reading:**

-   Grimmer, J., Roberts, M. E., & Stewart, B. M. (2022). Text as data: A new framework for machine learning and the social sciences. Princeton University Press. Chapter 2.

And one of the three below:

-   Political Science Perspective: [Wilkerson, J. and Casas, A. (2017). Large-Scale Computerized Text Analysis in Political Science: Opportunities and Challenges. Annual Review of Political Science, 20, 529:544.](https://www.annualreviews.org/doi/abs/10.1146/annurev-polisci-052615-025542?journalCode=polisci)

-   Economics Perspective: [Gentzkow, Matthew, Bryan Kelly, and Matt Taddy. "Text as data." Journal of Economic Literature 57, no. 3 (2019): 535-574.](https://web.stanford.edu/~gentzkow/research/text-as-data.pdf)

-   Sociology Perspective: <https://www.sciencedirect.com/science/article/pii/S0049089X22000904>

**Additional Readings:**

-   Text Pre-Processing: [Denny, M. J., & Spirling, A. (2018). Text preprocessing for unsupervised learning: why it matters, when it misleads, and what to do about it. Political Analysis, 26(2): 168-189.](https://www.cambridge.org/core/journals/political-analysis/article/abs/text-preprocessing-for-unsupervised-learning-why-it-matters-when-it-misleads-and-what-to-do-about-it/AA7D4DE0AA6AB208502515AE3EC6989E)

-   Descriptive Analysis of Text: TO ADD

-   Topic models : [Roberts, Margaret E., et al. "Topic models for open ended survey responses with applications to experiments." American Journal of Political Science 58 (2014): 1064-82](https://scholar.harvard.edu/files/dtingley/files/topicmodelsopenendedexperiments.pdf)
