---
title: "Week 09"
subtitle: "Apis + Selenium"
description: ""
author: "Tiago Ventura"
date: "10/31/2023"
#listing:
  # - id: slides
  #   contents:
  #     - ../slides/week-01/*.qmd
  #   type: table
  #   fields: [title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     title: "Topic"
  #     date: "Date"
  #   sort: [filename]
  #   sort-ui: false
  #   filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Lectures Notes:

-   APIs [html](/lecture_notes/week-09/_week-08_apis.html) -- <a href="/lecture_notes/week-09/_week-08_apis.ipynb" download> Jupyter Notebook </a>

-   Selenium [html](/lecture_notes/week-09/_week-08_selenium.html) -- <a href="/lecture_notes/week-09/_week-08_selenium.ipynb" download> Jupyter Notebook </a>

# Slides

-   [Acquiring data on the Web: APIs and Selenium](/slides/week-9.html)

# Readings

**APIs**

-   Nice overview about APIs from Chris Bail [here](https://cbail.github.io/textasdata/apis/rmarkdown/Application_Programming_interfaces.html). (it is in R, so pay more attention to the concepts)

**Selenium**

-   [Tutorial Webscrapping using Selenium](https://iqss.github.io/dss-webscrape/index.html)

-   Set up your selenium environment: <https://selenium-python.readthedocs.io/installation.html>

-   Web Driver Manager library in Python: <https://pypi.org/project/webdriver-manager/>

-   Locating elements in Selenium: <https://selenium-python.readthedocs.io/locating-elements.html>

**Applied Research**

-   [Trielli, Daniel, and Nicholas Diakopoulos. "Search as news curator: The role of Google in shaping attention to news information." In Proceedings of the 2019 CHI Conference on human factors in computing systems, pp. 1-15. 2019.](https://dl.acm.org/doi/pdf/10.1145/3290605.3300683)

-   [Haroon, Muhammad, Anshuman Chhabra, Xin Liu, Prasant Mohapatra, Zubair Shafiq, and Magdalena Wojcieszak. "YouTube, the great radicalizer? Auditing and mitigating ideological biases in YouTube recommendations." arXiv preprint arXiv:2203.10666 (2022).](https://arxiv.org/abs/2203.10666)
