---
title: "<span style = 'font-size: 80%;'> Week 1: Introductions, Installations, IDEs, Command line </span> "
author: "Professor: Tiago Ventura <br> Data Science for Public Policy <br> McCourt School, Georgetown University"
date: " <span style = 'font-size: 60%;'> 05/05/2023 </span>"
output:
  xaringan::moon_reader:
    css: ["xaringan-themer.css", "custom.css"]
    lib_dir: libs
    self_contained: false
    nature:
      #ratio: 16:9
      #ratio: 191:100
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "Slide %current% of %total%" # Slide 12 of 42
---

layout: true

::: my-footer
PPOL 5203 - Data Science I: Foundations
:::

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(messagwese=FALSE, warning = FALSE)
xaringanthemer::style_mono_light(base_color ="#23395b", 
                                  title_slide_text_color="#ffff", 
                                  title_slide_background_color = "#23395b", 
                                  background_color = "#fff", 
                                  link_color =  "#DA291C")
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(message=FALSE, warning = FALSE, error=TRUE, echo=FALSE, cache=TRUE)
```

```{r style-share-again, echo=FALSE}
xaringanExtra::use_tile_view()
xaringanExtra::use_panelset()

#xaringanExtra::style_share_again(
#  share_buttons = c("twitter", "linkedin", "pocket")
#)
```

## Hi

Test
